"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { StyledFirebaseAuth } from "react-firebaseui";
import firebase from "firebase/compat/app";
import "firebase/compat/auth";

import "./globals.css";
import Navbar from "./components/Navbar";
import { auth } from "../../firebase/firebase";
import Loader from "./components/Loader";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

const uiConfig = {
    signInFlow: "popup",
    signInOptions: [firebase.auth.GoogleAuthProvider.PROVIDER_ID],
    signInSuccessUrl: "/",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const [isSignedIn, setIsSignedIn] = useState(false);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const unregisterAuthObserver = auth.onAuthStateChanged((user) => {
            setIsSignedIn(!!user);
            setLoading(false);
        });
        return () => unregisterAuthObserver();
    }, []);

    const content = !isSignedIn ? (
        <html lang="en">
            <body className={inter.className}>
                {loading ? (
                    <Loader />
                ) : (
                    <div className={styles.authentication}>
                        <h1>Gym Tracker</h1>
                        <p>Please sign-in:</p>
                        <StyledFirebaseAuth
                            uiConfig={uiConfig}
                            firebaseAuth={auth}
                        />
                    </div>
                )}
            </body>
        </html>
    ) : (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
    return content;
}
